name: Static Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'MendaciumB/link_bio
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: Run build script
      run: ./link_bio/remote_build.sh

    - name: Commit and Push changes
      uses: tefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update static build
        commit_user_name: Menda [GitHub Actions]
        commit_user_email: Brayhansantamaria203@gmail.com
        commit_author: MendaciumB
